spring.application.name=CorretoraAcademico
brapi.token=n1RQ11hfB8MhdLjCUuh8rk
alphavantage.key=CTBDQZZCONDWHNSE
twelvedata.key=1024ca6066ac4e259de3172afc596346


spring.datasource.url=jdbc:h2:mem:CorretoraAcademico
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console